spring:
  profiles:
    active: native
  
management:
  security:
  enabled: false

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30   #续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 90  #续约到期时间（默认90秒）
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    healthcheck:
      enabled: true   #开启健康检查（需要spring-boot-starter-actuator依赖）



